#!/bin/sh

file="$1"
shift
if [ ! -e $file ]; then
$@
exit $?
fi

cachedir=${XDG_CACHE_HOME:-$HOME/.cache}
changelogf=$cachedir/logs/changedlogf.yml

if [ -d $file]; then opt="-r"; fi
qm=$(ipfs add -Q -n $opt $file --progress=false)
if last=$(grep -e "$file" $changelogf | tail -1); then
 #echo last: $last
 prev=$(echo $last | cut -d: -f1)
 if [ "z$qm" != "z$prev" ]; then
   echo prev: $prev
   echo "qm: $qm (new)"
   echo "$qm: $file" >> $changelogf
   if [ "c$1" != 'c' ]; then
     echo "cmd: $@"
     $@
     exit $?
   else
     exit 0
   fi
 else 
   echo -n "qm: $qm (same)\r"
   exit 1
 fi
fi


