#!/usr/bin/perl
BEGIN { $update=1;$verbose=0; my$p=rindex($0,'/');our$bindir=($p>0)?substr($0,0,$p):'.'; } # for SITE.pm

# next release
use Time::Local qw(timelocal);
my $_1day = 24 * 3600;
my $period = $_1day * 7 / 4;

my $tic = time;
my $wday = (localtime($tic))[6];
my ($hour,$mday,$mon,$yy) = (localtime($tic -  $wday * 24 * 3600 ))[2..5];
my $sunday = timelocal(0,0,0,$mday,$mon,1900+$yy);
#printf "sunday: %s.%s.%s\n",$mday,$mon+1,1900+$yy;

my $tic = $sunday + (1 + int((time - $sunday)/$period)) * $period - 1;

use lib $bindir;
use SITE qw();
use UTIL qw(rev);

my ($m,$r) = &rev($tic);
printf "major: %.2f\n",int($m/10)/10;
printf "release: %.2f -- %s (v%.1f.%d)\n",($m+$r)/100,&hdate($tic),int($m/10)/10,$m%10+$r;

local *EXEC; open EXEC, '|espeak -a 180';
printf EXEC "release: %.2f -- %s (version %.1f.%d)\n",($m+$r)/100,&ldate($tic),int($m/10)/10,$m%10+$r;
close EXEC;

# -----------------------------------------------------------------------
sub ldate { # return long date
  my ($time,$delta) = @_;
  my $stamp = $time+$delta;
  my $tic = int($stamp);
  #my $ms = ($stamp - $tic)*1000;
  my $LDoW = [qw( Sunday Monday Tuesday Wednesday Thursday Friday Saturday )];
  my $LMoY = [qw( January Febuary March April May June July August September October November December )];
  my ($sec,$min,$hour,$mday,$mon,$yy,$wday) = (localtime($tic))[0..6];
  my ($yr4,$yr2) =($yy+1900,$yy%100);

  # Mon, 01 Jan 2010 00:00:00 GMT
  my $date = sprintf '%3s, %2d %3s %04u %02u hour local time',
             $LDoW->[$wday],$mday,$LMoY->[$mon],$yr4, $hour+1;
  return $date;
}
# -----------------------------------------------------------------------
sub hdate { # return HTTP date (RFC-1123, RFC-2822) 
  my ($time,$delta) = @_;
  my $stamp = $time+$delta;
  my $tic = int($stamp);
  #my $ms = ($stamp - $tic)*1000;
  my $DoW = [qw( Sun Mon Tues Wed Thur Fri Sat )];
  my $MoY = [qw( Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec )];
  my ($sec,$min,$hour,$mday,$mon,$yy,$wday) = (gmtime($tic))[0..6];
  my ($yr4,$yr2) =($yy+1900,$yy%100);

  # Mon, 01 Jan 2010 00:00:00 GMT
  my $date = sprintf '%3s, %02d %3s %04u %2u:%02u GMT',
             $DoW->[$wday],$mday,$MoY->[$mon],$yr4, $hour,$min;
  return $date;
}
# -----------------------------------------------------------------------
1;
