#!/usr/bin/perl

local $/ = undef;
my $buf = <STDIN>;
use YAML::Syck qw(Load Dump);

$buf = "--- \n" . $buf if ($buf !~ m/^---/);
$buf =~ y/\t/ /;
#printf "buf: %s\n",$buf;

my $yml = Load($buf);
#printf "yml: %s\n",Dump($yml);

my $LF = ($#ARGV > 0) ? "\n" : '';
if (@ARGV) {
foreach (@ARGV) {
  my $p = rindex($_,'.');
  my $key=substr($_,0,$p);
  my $subkey=substr($_,$p+1);
  #printf "key: %s\n",$key;
  #printf "subkey: %s\n",$subkey; exit;
  if (ref($yml->{$key}) eq 'ARRAY') {
    print $yml->{$key}[$subkey],$LF;
  } elsif (ref($yml->{$key}) eq 'HASH') {
    print $yml->{$key}{$subkey},$LF;
  } elsif (ref($yml->{$_}) eq 'HASH') {
    print Dump($yml->{$_}),$LF;
  } else {
    print $yml->{$_},$LF;
  }
}
} else {
 printf "%s...\n",YAML::Syck::Dump($yml);
}

exit $?;
1;
